[project]
name = "spectral-clustering"
version = "0.0.1"
description = "Finding patterns in dynamical systems."
readme = "README.md"
authors = [
    { name = "Víctor López", email = "217356204+victor-lopz@users.noreply.github.com" }
]
requires-python = ">=3.14.5"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pre-commit>=4.6.2",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.0",
]

[tool.uv]
package = false
