name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    name: "Lint & format"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: "Check format & lint"
        id: run_pre_commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true

      - name: "Fix code formatting with pre-commit-ci-lite"
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: "🎨 Auto format code"

      - name: "Check remaining errors"
        if: steps.run_pre_commit.outcome == 'failure'
        run: exit 1

